version: '3.8'
services:
  hurricane-model-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hurricane-model-server
    ports:
      - "5000:5000"
    environment:
      - MODEL_PATH=hurricane_damage_model.h5
      - PORT=5000
    restart: unless-stopped
