version: '3.8'
services:
  hurricane-model-server:
    image: yourusername/hurricane-damage-model:latest
    container_name: hurricane-model-server
    ports:
      - "5000:5000"
    environment:
      - MODEL_PATH=hurricane_damage_model.h5
      - PORT=5000
    restart: unless-stopped
    # Add resource limits for the more complex model
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G